### ISSUE TITLE
Task - Raw download hub

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1009]
## Task - Raw download hub

While most tables can be downloaded as raw data through their individual cards, this is far from optimal from a ease of use perspective, and it obscures what data are used in what "domain".  Elements of this are similar to the experimental "cards per domain" tab we had early on in TW.

As a user I want to visit a hub task and download all data related to my domain/use case.  I should be able to click a button and recieve a tar/gzip of all the individual tables.  _There is no filtering here at this point, just a dump of everything.  This is a potential downside for big projects._

## Implementation
* [ ] Write a constant config file in YAML.  Keys are domain names.  Values are a hash with two keys: `:models` and `:tables`.  The latter is used to link to join or other tables that are not exposed as Data cards.  Perhaps this could be unified.
* [ ] Map the config to a constant
* [ ] Create a "Package"  lib that can produce the Tar/Gzip of the various tables
* [ ] Use a tempfile to serve a temporary version of the Gzip
* [x] Consider use of DelayedJob for large downloads (this is likely unnecessary).

### Interface
* [x] Add the task
* [ ] Foreach domain create a table with links to Download for each model
* [ ] Below the table create a link to the Temp GZIP
* [x] Add functionality for callbacks for longer jobs

### Nomenclature
```yaml
nomenclature: 
  models: 
     - taxon_name
     - taxon_name_classification
     - taxon_name_relationship
     - source
     - person
     - citation
  tables:
     - roles
```
