### ISSUE TITLE
Task - "Naive" nomenclature checklist

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1183]
As a user I want to dump checklist of nomenclature. I believe the intent is upload into a Symbiota-based portal (e.g. SCAN).  

* [ ] Is this really the ideal format, or should it be more native. 
* [ ] Can we serve this directly via an API endpoint (yes) so that user download/uploads into X are not necessary?
* [ ] This doesn't seem very sustainable as subsequent merges will be string based, we can do better, in theory, by including IDs.  Thoughts?

* Order
* Infraorder
* Superfamily
* FAMILY
* SUBFAMILY
* GENUS
* SPECIES
* subspecies
* Author
* YEAR
* SYNONYM(S)
* < SOME OTHER COLUMN>
* Fossil

Ping @egbot.

**Comment by juliema** [comment]
I think <SOME OTHER COLUMN> can be removed -- I did not see anything in the spreadsheet there.
