### ISSUE TITLE
Task: geography based checklist (NatureServe)

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#2367]
As  curator, I want to produce a list of species scoped by geographic regions.

**Comment by jrflood** [comment]
The initial set of data was produced through SQL query of SFdb for Plecoptera (of North America).  Taxa which had recorded TDWG distribution data were selected for valid, synonym, and nomen dubium name status.  Due to the particular way certain data are recorded only in the valid name, the parent taxon name ID (AboveID) is used to select taxa for nomina dubia and synonyms.  

This is a sort of inverse to the report table of issue #2046.

**Comment by proceps** [comment]
I think it should be implemented as a part of OTU Filter development.

**Comment by mjy** [comment]
@proceps you are right, the `otu/filter.rb` will have the code to return the records, this is targeting a task/view that will display the result in the correct format.

@jrflood please post the export format here. @debpaul can you comment as to whether that format is in fact a DwC checklist when it arrives.

**Comment by proceps** [comment]
I would say, we should try to replicate Endemism task format where all distribution records normolized to valid names and all names returned in hierarchical order.

**Comment by mjy** [comment]
This comes out of a specific request to us from NatureServ, so generalizing it might be useful, but the issue does have a specific goal.

**Comment by jrflood** [comment]
![Screen Shot 2021-07-27 at 3 47 54 PM](https://user-images.githubusercontent.com/5349955/127225146-e064b817-7e89-4464-86a4-f3ab44d9e583.png)

**Comment by debpaul** [comment]
Looking now from these guidelines.

- #GBIF [DQ Requirements for Checklists](https://www.gbif.org/data-quality-requirements-checklists). 
- And comparing to a [sample dataset](http://data.canadensys.net/ipt/archive.do?r=vascan). 
    - from [GBIF Checklist Data Templates](https://github.com/gbif/ipt/wiki/checklistData#templates). 

Feedback.

1. the screen shot from @jrflood has no associated geographic region information. Are these data for a given region? If so, would need to put in a separate related file. (see above example dataset).
2. a GBIF Checklist also has an eml.xml file.
3. Likely easiest to create a compliant checklist using the IPT which will generate the other expected files.

I don't know what NatureServ is hoping for/expects?

Checklist Expectations (minimal) and all of these are in the above screenshot.
  -  [x] taxonID (req'd)
  -  [x] scientificName (req'd)
  -  [x] taxonRank
  -  [x] kingdom
  -  [x] parentNameUsageID
  -  [x] acceptedNameUsageID

**Dataset metadata (EML)** (all fields req'd except bibliographicCitation)

  - [ ] title    (the title under which the dataset will be published at GBIF)
  - [ ] description   (English language text, describing the dataset.)
  - [ ] publisher    (title of the institution or organization that will be listed as the data publisher at gbif.org.)
  - [ ] type      (type of the dataset. Here: "checklist".)
  - [ ] license      (A machine-readable statement of the rights attached to the published dataset. Use either CC0 or CC BY.)
  - [ ] contact      (Contact data (minimum: name and email) for at least one administrative contact for the dataset.)
  - [ ] creator     (Contact data (minimum: name and email) for the creator of the dataset)
  - [ ] metadata provider      (Contact data (minimum: name and email) for the author of the dataset metadata)  
  - [ ] bibliographicCitation     (a text specifying how your dataset should be cited in publications that make use of your data.)   (strongly recommended)

Is this what was needed @mjy? If you need more info, I can meet with Rich to go farther ...

**Comment by tmcelrath** [comment]
This would also be useful to me.

**Comment by mjy** [comment]
Marking as duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/2069
