### ISSUE TITLE
Product - As a botanist I want to generate annotated checklist in botanical "format"

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#4116]
An enquiry from Quentin.

See https://phytokeys.pensoft.net/articles.php?id=127527&journal_name=phytokeys

Building this out very much follows the existing  "paper catalog" (PC) strategy.  Going through the above paper the following list are things we've coded, not:

* [x] Advanced integrated reference management and object "citability", with ability to specify existience of specific "topics' (this taxon in this publication has something about x, y, z, keys, images...)
* [x] Basic botanical name handling
* [x] Repository refrences and summaries (sensu PC), i.e ability to do "CPUN, CUZ, HA, HUT, HUTI, LOJA, MA, Q, QAP, QC..."
* [x] Specimen digitization, georeferencening, etc.
* [x] Literature referencs to distributions
* [ ] Material examined sections.  Core in-scope functionality, but not done yet. We've done this in precursor software, its well understood and a medimum-level priority (hope to demo some things by May [TWT](https://together.taxonworks.org/)).
* [x] Distribution summaries.  Since TW handles specimens, literature, and field-observations we can summarize across these worlds.  Queries to do this exist, fairly straight forward aggregating/summarizing functions vairiously exist, they could be tweaked for this format.
* [x] Text sections (like Note, Distribution, Taxonomic notes).  Well developed as "Content" in TaxonWorks.  See Topics and the Content editor.
* [x] Type specimen handling/rendering. We have explicit TypeMaterial models, extremely rich specimen digitization, and methods to summarize data into concise human readable strings.
* [ ] Wrapping "Catalog" data-structure.  We have existing generic code that facilitates "entries" and "entry-items" that we can use to group data into units to render.  We'd need a new module/class specific to the botanical checklist format above.
* [ ] Rendering of "Catalog" data-structuer.  Here we would likely follow the pattern used in PaperCatlaog where we render a Markdown format then tranform it into other document formats as needed (pdf, word, e-book). 
... more as we think of them.

Some questions regarding downstream publication come to mind:
* Pensofts publishing tools structure many of these sections.  I haven't recently looked at whether structured data can be sumbitted at the whole publication level, this would be ideal rather than re-keying TW data into their formats.  I'm certain they'd be happy to outline what they have, we have danced to the side of them for a very very long time. I suspect advancing a conversation with publishers would best be facilitated if we can come to the table with a "fully" realized product.
