### ISSUE TITLE
Task - New combination - issues

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#496]
* [x] When I a working on the 3i database, the form is extremely slow, it takes 20-30 seconds to resolve a single name, especially if the name is common "Zygina alba" for example. It is slow to the level it is almost impossible to use the form for the efficient data editing.
* [ ] One way to slightly improve is to restrict search to ICZN names only. In botany people do not use combinations [now #893]
* [x] When both genus and subgenus are present in the database, both names are proposed, and there is no way to distinguish them. There should be only a single option available.
* [ ] When I provided the species author, I should restrict my search to the species described by this author only. [now #894]
* [ ] When I move mouse over the taxon name, the name should not jump. Any reaction to the mouse over, should not trigger the page content jump. [Now #895]
* [ ] ~~Taxon name should have links to Browse nomenclature for preview purposes~~ (re-open, new autocomplete option includes original combination if you need to get context, if original combination not in there you probably shouldn't be using the form at that point?)
* [ ] Making search for an existing combination, does not return me an existing combination as "Already exists" option [Now #896]
* [ ] ~~Search for genus, subgenus, species and subspecies, should be available from the very beginning, not hidden before you made a search.~~ No, definitely not, drastically complicates user interface (and implementation) and defeats existing magic.  Remember this can be unlocked in times it's needed.  If we really need this to start we'll make a new task.
* [ ] ~~Once one of the name is selected (by mistake) there is no way to deselect it.~~ Use "unlock"

**Comment by mjy** [comment]
@proceps There is a lot going on here- each of these bullet points should likely be its own issue?

**Comment by mjy** [comment]
Confirmed the slowness for that query.  I suspect we're missing something obvious that we can speed things up with, will just have to look.

**Comment by mjy** [comment]
Can you find other slow queries?  Using the UCD data it's easily fast enough for similar size result sets.

**Comment by proceps** [comment]
in 3i database, I run "Diplocolenus (Zygina) abdominalis alba" combination, it takes more than 5 min now to process. Have not finished yet.

**Comment by jlpereira** [comment]
Just to confirm that, are you seeing the spinner? have you check the browser console to see if you're getting an error related with javascript?

**Comment by proceps** [comment]
Ok, I restarted the search. It took more than a minute for 4 name combination. The spinner was working in both cases.

**Comment by jlpereira** [comment]
Try it with the browser console open, the spinner could hang if its getting a javascript error

**Comment by proceps** [comment]
Last one finished in just over one min.

**Comment by mjy** [comment]
@jlpereira making you a member, it's at sandstorm

**Comment by mjy** [comment]
In console query `Diplocolenus (Zygina) abdominalis alba` is timing out with a 503, Service Unavailable after a minute or two.

**Comment by mjy** [comment]
Might be server or @proceps' data import related.  The `Diplocolenus (Zygina) abdominalis alba` query in the sandbox version of 3i on my laptop takes less than 3 seconds.

**Comment by mjy** [comment]
Mmm- on second look, the link is not broken, it's just sending a pdf (http://www.geo-locate.org/files/glcJSON.pdf)

**Comment by mjy** [comment]
See individualized issues.
